name: github-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM dependencies
        run: npm install
      - name: Build distributables
        run: |
          # --- Create dist directory, containing the final website structure
          mkdir dist

          # --- Copy base HTML + favicon
          cp assets/pages/index.html dist
          cp assets/images/favicon.ico dist

          # --- Copy assets
          cp -r assets dist

          # --- Copy JS files (no build step for now)
          mkdir dist/build/js
          cp -r src/js dist/build/js

          # --- Compile Stylus to CSS
          npx stylus src/stylus -o dist/build/css -c --include-css

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
